import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'
import { Control } from './Control';

interface TopicInfo {
  id: number;
  title: string;
  body: string;
}
export const metadata: Metadata = {
  title: 'Hello, WEB',
  description: 'Generated by JDG',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const resp = await fetch('http://localhost:9999/topics', { cache: 'no-store' });
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1><Link href='/'>WEB</Link></h1>
        <ol>
          {topics.map((topic: TopicInfo) => {
            return (<li key={topic.id}>
              <Link href={'/read/' + topic.id}>
                {topic.title}
              </Link>
            </li>)
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  )
}
